// ============================================================
// DADOS FICTÍCIOS PARA AMBIENTE DE HOMOLOGAÇÃO / REVISÃO TÉCNICA
// NÃO UTILIZAR EM PRODUÇÃO
// ============================================================

export const DEMO_USER = {
  id: 'demo-user-0001',
  email: 'demo@cps.pa.gov.br',
  created_at: '2025-01-01T00:00:00Z',
};

export const DEMO_PROFILE = {
  id: 'demo-user-0001',
  email: 'demo@cps.pa.gov.br',
  full_name: 'Avaliador Técnico (Demo)',
  role: 'admin',
};

export const DEMO_CREDENTIALS = {
  email: 'demo@cps.pa.gov.br',
  password: 'homologacao2026',
};

// ─────────────────────────────────────────────────────────
// CANDIDATOS
// ─────────────────────────────────────────────────────────
export const demoCandidatos = [
  {
    id: 'cand-001',
    nome: 'Ana Paula Teixeira Barbosa',
    cpf: '123.456.789-00',
    email: 'ana.teixeira@gmail.com',
    telefone: '(91) 98201-3344',
    cargo: 'Professora de Matemática',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Belém',
    status: 'Classificado',
    pontuacao: 92.5,
    documentos: ['RG', 'CPF', 'Diploma', 'Histórico Escolar'],
    historico: [
      { data: '10/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '22/01/2026', evento: 'Documentos Validados', usuario: 'Admin' },
      { data: '05/02/2026', evento: 'Classificado', usuario: 'Admin' },
    ],
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'cand-002',
    nome: 'Carlos Eduardo Mendes Silva',
    cpf: '234.567.890-11',
    email: 'carlos.mendes@hotmail.com',
    telefone: '(91) 99302-5511',
    cargo: 'Professor de Português',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Ananindeua',
    status: 'Em Análise',
    pontuacao: 78.0,
    documentos: ['RG', 'CPF', 'Diploma'],
    historico: [
      { data: '11/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '23/01/2026', evento: 'Em Análise Documental', usuario: 'Admin' },
    ],
    created_at: '2026-01-11T10:30:00Z',
  },
  {
    id: 'cand-003',
    nome: 'Fernanda Lima Rodrigues',
    cpf: '345.678.901-22',
    email: 'fernanda.lima@yahoo.com.br',
    telefone: '(91) 98403-7722',
    cargo: 'Professora de Ciências',
    processo: 'PSS SEDUC 002/2026',
    localidade: 'Marabá',
    status: 'Aprovado',
    pontuacao: 95.0,
    documentos: ['RG', 'CPF', 'Diploma', 'Certificado de Especialização'],
    historico: [
      { data: '15/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '28/01/2026', evento: 'Aprovada — Resultado Final', usuario: 'Gestor' },
    ],
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'cand-004',
    nome: 'Roberto Alves Pereira',
    cpf: '456.789.012-33',
    email: 'roberto.alves@gmail.com',
    telefone: '(94) 98504-6633',
    cargo: 'Professor de Educação Física',
    processo: 'PSS SEDUC 002/2026',
    localidade: 'Santarém',
    status: 'Com Pendência',
    pontuacao: 65.0,
    documentos: ['RG', 'CPF'],
    historico: [
      { data: '16/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '29/01/2026', evento: 'Pendência: Faltam documentos', usuario: 'Admin' },
    ],
    created_at: '2026-01-16T11:00:00Z',
  },
  {
    id: 'cand-005',
    nome: 'Juliana Carvalho Nascimento',
    cpf: '567.890.123-44',
    email: 'juliana.carvalho@gmail.com',
    telefone: '(91) 98605-4455',
    cargo: 'Professora de História',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Belém',
    status: 'Classificado',
    pontuacao: 88.5,
    documentos: ['RG', 'CPF', 'Diploma', 'Histórico Escolar'],
    historico: [
      { data: '12/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '25/01/2026', evento: 'Classificada', usuario: 'Admin' },
    ],
    created_at: '2026-01-12T09:30:00Z',
  },
  {
    id: 'cand-006',
    nome: 'Marcos Vinicius Santos Moura',
    cpf: '678.901.234-55',
    email: 'marcos.moura@outlook.com',
    telefone: '(93) 98706-3366',
    cargo: 'Professor de Física',
    processo: 'PSS SEDUC 003/2026',
    localidade: 'Altamira',
    status: 'Homologado',
    pontuacao: 91.0,
    documentos: ['RG', 'CPF', 'Diploma', 'Lattes'],
    historico: [
      { data: '05/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '20/01/2026', evento: 'Homologado', usuario: 'Gestor' },
    ],
    created_at: '2026-01-05T14:00:00Z',
  },
  {
    id: 'cand-007',
    nome: 'Patricia Souza Oliveira',
    cpf: '789.012.345-66',
    email: 'patricia.souza@gmail.com',
    telefone: '(91) 98807-2277',
    cargo: 'Coordenadora Pedagógica',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Castanhal',
    status: 'Em Análise',
    pontuacao: 74.0,
    documentos: ['RG', 'CPF', 'Diploma'],
    historico: [
      { data: '13/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
    ],
    created_at: '2026-01-13T08:15:00Z',
  },
  {
    id: 'cand-008',
    nome: 'Diego Fernando Costa Araújo',
    cpf: '890.123.456-77',
    email: 'diego.araujo@gmail.com',
    telefone: '(91) 98908-1188',
    cargo: 'Professor de Química',
    processo: 'PSS SEDUC 003/2026',
    localidade: 'Barcarena',
    status: 'Classificado',
    pontuacao: 85.5,
    documentos: ['RG', 'CPF', 'Diploma', 'Histórico Escolar'],
    historico: [
      { data: '06/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '21/01/2026', evento: 'Classificado', usuario: 'Admin' },
    ],
    created_at: '2026-01-06T10:00:00Z',
  },
  {
    id: 'cand-009',
    nome: 'Letícia Ferreira Gomes',
    cpf: '901.234.567-88',
    email: 'leticia.gomes@gmail.com',
    telefone: '(91) 98109-0099',
    cargo: 'Professora de Arte',
    processo: 'PSS SEDUC 002/2026',
    localidade: 'Paragominas',
    status: 'Desclassificado',
    pontuacao: 42.0,
    documentos: ['RG', 'CPF'],
    historico: [
      { data: '17/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '30/01/2026', evento: 'Desclassificada — Nota Insuficiente', usuario: 'Admin' },
    ],
    created_at: '2026-01-17T11:30:00Z',
  },
  {
    id: 'cand-010',
    nome: 'Anderson Lima Monteiro',
    cpf: '012.345.678-99',
    email: 'anderson.monteiro@hotmail.com',
    telefone: '(91) 98210-9900',
    cargo: 'Professor de Inglês',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Igarapé-Miri',
    status: 'Em Análise',
    pontuacao: 69.5,
    documentos: ['RG', 'CPF', 'Diploma'],
    historico: [
      { data: '14/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
    ],
    created_at: '2026-01-14T13:00:00Z',
  },
  {
    id: 'cand-011',
    nome: 'Vanessa Miranda Correa',
    cpf: '111.222.333-44',
    email: 'vanessa.correa@gmail.com',
    telefone: '(91) 98311-8811',
    cargo: 'Professora de Geografia',
    processo: 'PSS SEDUC 002/2026',
    localidade: 'Belém',
    status: 'Classificado',
    pontuacao: 87.0,
    documentos: ['RG', 'CPF', 'Diploma', 'Histórico Escolar'],
    historico: [
      { data: '18/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '31/01/2026', evento: 'Classificada', usuario: 'Admin' },
    ],
    created_at: '2026-01-18T09:00:00Z',
  },
  {
    id: 'cand-012',
    nome: 'Bruno Rafael Nunes Feitosa',
    cpf: '222.333.444-55',
    email: 'bruno.nunes@gmail.com',
    telefone: '(92) 98412-7722',
    cargo: 'Professor de Filosofia',
    processo: 'PSS SEDUC 003/2026',
    localidade: 'Tucuruí',
    status: 'Homologado',
    pontuacao: 93.5,
    documentos: ['RG', 'CPF', 'Diploma', 'Lattes', 'Certificado'],
    historico: [
      { data: '07/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '22/01/2026', evento: 'Homologado', usuario: 'Gestor' },
    ],
    created_at: '2026-01-07T12:00:00Z',
  },
  {
    id: 'cand-013',
    nome: 'Camila Duarte Ramos',
    cpf: '333.444.555-66',
    email: 'camila.ramos@yahoo.com',
    telefone: '(91) 98513-6633',
    cargo: 'Professora de Biologia',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Benevides',
    status: 'Com Pendência',
    pontuacao: 70.0,
    documentos: ['RG'],
    historico: [
      { data: '19/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '01/02/2026', evento: 'Pendência: Diploma não enviado', usuario: 'Admin' },
    ],
    created_at: '2026-01-19T10:00:00Z',
  },
  {
    id: 'cand-014',
    nome: 'Ricardo Augusto Pinheiro Luz',
    cpf: '444.555.666-77',
    email: 'ricardo.pinheiro@gmail.com',
    telefone: '(94) 98614-5544',
    cargo: 'Psicólogo Escolar',
    processo: 'PSS SEDUC 004/2026',
    localidade: 'Redenção',
    status: 'Aprovado',
    pontuacao: 96.0,
    documentos: ['RG', 'CPF', 'Diploma', 'CRP', 'Histórico Escolar'],
    historico: [
      { data: '20/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '02/02/2026', evento: 'Aprovado — Melhor Classificado', usuario: 'Gestor' },
    ],
    created_at: '2026-01-20T08:30:00Z',
  },
  {
    id: 'cand-015',
    nome: 'Priscila Gonçalves Batista',
    cpf: '555.666.777-88',
    email: 'priscila.batista@gmail.com',
    telefone: '(91) 98715-4455',
    cargo: 'Assistente Social',
    processo: 'PSS SEDUC 004/2026',
    localidade: 'Santarém',
    status: 'Em Análise',
    pontuacao: 71.5,
    documentos: ['RG', 'CPF', 'Diploma', 'CRESS'],
    historico: [
      { data: '21/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
    ],
    created_at: '2026-01-21T09:15:00Z',
  },
  {
    id: 'cand-016',
    nome: 'Felipe Andrade Tavares',
    cpf: '666.777.888-99',
    email: 'felipe.tavares@gmail.com',
    telefone: '(91) 98816-3366',
    cargo: 'Professor de Matemática',
    processo: 'PSS SEDUC 001/2026',
    localidade: 'Belém',
    status: 'Classificado',
    pontuacao: 82.0,
    documentos: ['RG', 'CPF', 'Diploma'],
    historico: [
      { data: '22/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '03/02/2026', evento: 'Classificado', usuario: 'Admin' },
    ],
    created_at: '2026-01-22T11:00:00Z',
  },
  {
    id: 'cand-017',
    nome: 'Aline Fonseca Bezerra',
    cpf: '777.888.999-00',
    email: 'aline.fonseca@hotmail.com',
    telefone: '(91) 98917-2277',
    cargo: 'Professora de Português',
    processo: 'PSS SEDUC 002/2026',
    localidade: 'Ananindeua',
    status: 'Homologado',
    pontuacao: 89.5,
    documentos: ['RG', 'CPF', 'Diploma', 'Histórico Escolar'],
    historico: [
      { data: '08/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '23/01/2026', evento: 'Homologada', usuario: 'Gestor' },
    ],
    created_at: '2026-01-08T14:00:00Z',
  },
  {
    id: 'cand-018',
    nome: 'Gabriel Henrique Azevedo Costa',
    cpf: '888.999.000-11',
    email: 'gabriel.azevedo@gmail.com',
    telefone: '(93) 98018-1188',
    cargo: 'Professor de Sociologia',
    processo: 'PSS SEDUC 003/2026',
    localidade: 'Altamira',
    status: 'Em Análise',
    pontuacao: 66.0,
    documentos: ['RG', 'CPF'],
    historico: [
      { data: '23/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
    ],
    created_at: '2026-01-23T10:30:00Z',
  },
  {
    id: 'cand-019',
    nome: 'Mariana Lobato Queirós',
    cpf: '999.000.111-22',
    email: 'mariana.lobato@gmail.com',
    telefone: '(91) 98119-0099',
    cargo: 'Fonoaudióloga Escolar',
    processo: 'PSS SEDUC 004/2026',
    localidade: 'Marabá',
    status: 'Aprovado',
    pontuacao: 94.0,
    documentos: ['RG', 'CPF', 'Diploma', 'CRFa'],
    historico: [
      { data: '09/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '24/01/2026', evento: 'Aprovada', usuario: 'Gestor' },
    ],
    created_at: '2026-01-09T08:00:00Z',
  },
  {
    id: 'cand-020',
    nome: 'Thiago Dantas Vasconcelos',
    cpf: '100.200.300-40',
    email: 'thiago.dantas@gmail.com',
    telefone: '(91) 98220-9900',
    cargo: 'Professor de Educação Especial',
    processo: 'PSS SEDUC 002/2026',
    localidade: 'Tucuruí',
    status: 'Desclassificado',
    pontuacao: 38.5,
    documentos: ['RG'],
    historico: [
      { data: '24/01/2026', evento: 'Inscrição Realizada', usuario: 'Sistema' },
      { data: '04/02/2026', evento: 'Desclassificado — Documentação Irregular', usuario: 'Admin' },
    ],
    created_at: '2026-01-24T11:00:00Z',
  },
];

// ─────────────────────────────────────────────────────────
// PROCESSOS SELETIVOS
// ─────────────────────────────────────────────────────────
export const demoProcessos = [
  {
    id: 'proc-001',
    nome: 'PSS SEDUC 001/2026 — Professores de Ensino Fundamental',
    descricao: 'Processo Seletivo Simplificado para contratação de professores de ensino fundamental nas áreas de Matemática, Português, História e Inglês na RMB.',
    fase_atual: 'Em Análise',
    progresso: 65,
    inicio: '2026-01-10',
    fim: '2026-03-31',
    created_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 'proc-002',
    nome: 'PSS SEDUC 002/2026 — Professores do Interior',
    descricao: 'Processo para professores das áreas de Ciências, Educação Física, Arte e Educação Especial para municípios do interior do Pará.',
    fase_atual: 'Inscrições Abertas',
    progresso: 40,
    inicio: '2026-01-15',
    fim: '2026-04-30',
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'proc-003',
    nome: 'PSS SEDUC 003/2026 — Professores de Ensino Médio',
    descricao: 'Seleção de professores de Física, Química, Filosofia e Sociologia para atendimento às demandas do ensino médio estadual.',
    fase_atual: 'Finalizado',
    progresso: 100,
    inicio: '2025-11-01',
    fim: '2026-01-31',
    created_at: '2025-10-28T10:00:00Z',
  },
  {
    id: 'proc-004',
    nome: 'PSS SEDUC 004/2026 — Profissionais de Apoio Pedagógico',
    descricao: 'Contratação de psicólogos, assistentes sociais e fonoaudiólogos para suporte à rede estadual de ensino.',
    fase_atual: 'Em Análise',
    progresso: 55,
    inicio: '2026-01-20',
    fim: '2026-03-15',
    created_at: '2026-01-15T11:00:00Z',
  },
  {
    id: 'proc-005',
    nome: 'PSS SEDUC 005/2026 — Professores de Educação Infantil',
    descricao: 'Seleção ordinária de professores para creches e pré-escolas da rede pública estadual.',
    fase_atual: 'Planejamento',
    progresso: 10,
    inicio: '2026-03-01',
    fim: '2026-05-30',
    created_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 'proc-006',
    nome: 'PSS CPS 001/2026 — Gestores Administrativos',
    descricao: 'Seleção de gestores para Coordenadorias Regionais de Ensino (CREs) no interior do estado.',
    fase_atual: 'Planejamento',
    progresso: 5,
    inicio: '2026-04-01',
    fim: '2026-07-01',
    created_at: '2026-02-10T09:00:00Z',
  },
];

// ─────────────────────────────────────────────────────────
// STATS DO DASHBOARD
// ─────────────────────────────────────────────────────────
export const demoStats = {
  candidatos: 1847,
  processos: 4,
  vagasPreenchidas: 312,
  atrasos: 3,
};

export const demoFunnelData = [
  { label: 'Inscritos Totais', count: 1847, color: '#6366f1' },
  { label: 'Em Análise', count: 934, color: '#8b5cf6' },
  { label: 'Classificados', count: 521, color: '#d946ef' },
  { label: 'Convocados', count: 312, color: '#10b981' },
];

// ─────────────────────────────────────────────────────────
// VAGAS POR LOCALIDADE (para Planejamento / ControleVagas)
// ─────────────────────────────────────────────────────────
export const mockControleVagas = [
  { id: 'vaga-001', matvin: '12345', servidor: 'Ana Paula Teixeira Barbosa', cargo_funcao: 'Professor de Matemática', atividade: 'Docência', vacancia: 'Não', status: 'OCUPADO', ultima_lotacao: 'Escola A', dre: 'DRE Belém', secretaria_pertencente: 'SEDUC', municipio: 'Belém', atendido_candidato: 'Sim', candidato_convocado: 'cand-001', observacao: '' },
  { id: 'vaga-002', matvin: '23456', servidor: 'Carlos Eduardo Mendes Silva', cargo_funcao: 'Professor de Português', atividade: 'Docência', vacancia: 'Não', status: 'OCUPADO', ultima_lotacao: 'Escola B', dre: 'DRE Ananindeua', secretaria_pertencente: 'SEDUC', municipio: 'Ananindeua', atendido_candidato: 'Sim', candidato_convocado: 'cand-002', observacao: '' },
  { id: 'vaga-003', matvin: null, servidor: null, cargo_funcao: 'Professor de Ciências', atividade: 'Docência', vacancia: 'Sim', status: 'LIVRE', ultima_lotacao: 'Escola C', dre: 'DRE Marabá', secretaria_pertencente: 'SEDUC', municipio: 'Marabá', atendido_candidato: 'Não', candidato_convocado: null, observacao: 'Vaga nova' },
  { id: 'vaga-004', matvin: null, servidor: null, cargo_funcao: 'Professor de História', atividade: 'Docência', vacancia: 'Sim', status: 'LIVRE', ultima_lotacao: 'Escola D', dre: 'DRE Santarém', secretaria_pertencente: 'SEDUC', municipio: 'Santarém', atendido_candidato: 'Não', candidato_convocado: null, observacao: 'Vaga nova' },
  { id: 'vaga-005', matvin: '34567', servidor: 'Fernanda Lima Rodrigues', cargo_funcao: 'Professor de Ed. Física', atividade: 'Docência', vacancia: 'Não', status: 'OCUPADO', ultima_lotacao: 'Escola E', dre: 'DRE Altamira', secretaria_pertencente: 'SEDUC', municipio: 'Altamira', atendido_candidato: 'Sim', candidato_convocado: 'cand-003', observacao: '' },
  { id: 'vaga-006', matvin: null, servidor: null, cargo_funcao: 'Professor de Física', atividade: 'Docência', vacancia: 'Sim', status: 'LIVRE', ultima_lotacao: 'Escola F', dre: 'DRE Belém', secretaria_pertencente: 'SEDUC', municipio: 'Belém', atendido_candidato: 'Não', candidato_convocado: null, observacao: 'Aposentadoria' },
  { id: 'vaga-007', matvin: null, servidor: null, cargo_funcao: 'Psicólogo Escolar', atividade: 'Apoio', vacancia: 'Sim', status: 'LIVRE', ultima_lotacao: 'DRE Belém', dre: 'DRE Belém', secretaria_pertencente: 'SEDUC', municipio: 'Belém', atendido_candidato: 'Não', candidato_convocado: null, observacao: 'Demanda Nova' },
  { id: 'vaga-008', matvin: '45678', servidor: 'Roberto Alves Pereira', cargo_funcao: 'Assistente Social', atividade: 'Apoio', vacancia: 'Não', status: 'OCUPADO', ultima_lotacao: 'DRE Paragominas', dre: 'DRE Paragominas', secretaria_pertencente: 'SEDUC', municipio: 'Paragominas', atendido_candidato: 'Sim', candidato_convocado: 'cand-004', observacao: '' },
  { id: 'vaga-009', matvin: null, servidor: null, cargo_funcao: 'Fonoaudióloga Escolar', atividade: 'Apoio', vacancia: 'Sim', status: 'LIVRE', ultima_lotacao: 'DRE Marabá', dre: 'DRE Marabá', secretaria_pertencente: 'SEDUC', municipio: 'Marabá', atendido_candidato: 'Não', candidato_convocado: null, observacao: 'Afastamento' },
  { id: 'vaga-010', matvin: '56789', servidor: 'Juliana Carvalho Nascimento', cargo_funcao: 'Coordenador Pedagógico', atividade: 'Gestão', vacancia: 'Não', status: 'OCUPADO', ultima_lotacao: 'Escola G', dre: 'DRE Castanhal', secretaria_pertencente: 'SEDUC', municipio: 'Castanhal', atendido_candidato: 'Sim', candidato_convocado: 'cand-005', observacao: '' },
];

// ─────────────────────────────────────────────────────────
// AUDITORIA
// ─────────────────────────────────────────────────────────
export const demoAuditLogs = [
  { id: 'audit-001', acao: 'UPDATE', tabela: 'candidatos', usuario_email: 'gestor@cps.pa.gov.br', descricao: "Status de 'Em Análise' → 'Classificado'", target_name: 'Ana Paula Teixeira Barbosa', created_at: '2026-02-05T14:30:00Z' },
  { id: 'audit-002', acao: 'INSERT', tabela: 'processos', usuario_email: 'admin@cps.pa.gov.br', descricao: 'Novo processo criado: PSS SEDUC 005/2026', target_name: 'PSS SEDUC 005/2026', created_at: '2026-02-01T09:00:00Z' },
  { id: 'audit-003', acao: 'UPDATE', tabela: 'candidatos', usuario_email: 'gestor@cps.pa.gov.br', descricao: "Status de 'Classificado' → 'Homologado'", target_name: 'Marcos Vinicius Santos Moura', created_at: '2026-01-20T11:00:00Z' },
  { id: 'audit-004', acao: 'DELETE', tabela: 'candidatos', usuario_email: 'admin@cps.pa.gov.br', descricao: 'Candidato removido por duplicidade de CPF', target_name: 'João Alves (Duplicado)', created_at: '2026-01-18T10:00:00Z' },
  { id: 'audit-005', acao: 'UPDATE', tabela: 'processos', usuario_email: 'admin@cps.pa.gov.br', descricao: "Fase: 'Inscrições Abertas' → 'Em Análise'", target_name: 'PSS SEDUC 001/2026', created_at: '2026-01-25T08:00:00Z' },
  { id: 'audit-006', acao: 'INSERT', tabela: 'candidatos', usuario_email: 'sistema@cps.pa.gov.br', descricao: '342 inscrições importadas do sistema legado', target_name: 'Importação em lote', created_at: '2026-01-10T07:00:00Z' },
];
